server:
  port: 8092

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:inventory-database}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        # Força o Hibernate a cuspir qualquer erro de schema no log
        hbm2ddl.auto: create

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      orchestrator: orchestrator
      inventory-success: inventory-success
      inventory-fail: inventory-fail

    properties:
      schema.registry.url: ${SCHEMA_REGISTRY:http://localhost:8081}

    consumer:
      group-id: product-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
       specific.avro.reader: true

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

# Desligar log do kafka
logging:
  level:
    org:
      apache:
        kafka: OFF
